spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: 158f15f3-83e0-4906-824c-69bdc50d9d61
        credential:
          client-id: 8e43eadc-4f43-4434-b074-7dd9b8d46468
          client-secret: OHk8Q~3T8exgtRx4bgkp6Xrqv4ryPYsnBb5FEaPW
        app-id-uri: api://8e43eadc-4f43-4434-b074-7dd9b8d46468

#          9f15860b-4243-4610-845e-428dc4ae43a
  datasource:
    url: jdbc:postgresql://localhost:5432/aituVolunteers
    username: postgres
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

frontend:
  uri:
    redirect: "http://localhost:3000/login"

image:
  storage:
    location: "C:/Users/koskakos/IdeaProjects/Ultimate/portfolio/aitu-volunteers/src/main/resources/static"

url: 'http://localhost:8080'